"""
Phase 8 — Streamlit Interactive Dashboard.

Run with:
    streamlit run app/dashboard.py

The dashboard has four tabs:
  1. Tournament Predictor  — WC 2026 probability table + heatmap
  2. Match Predictor       — pick any two teams, get win probabilities
  3. Team Rankings         — current Elo ratings and form stats
  4. Model Performance     — evaluation metrics and calibration notes
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# Make project root importable when launched from any directory
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="WC 2026 Predictor",
    page_icon="⚽",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Data loading (cached so it only runs once per session)
# ---------------------------------------------------------------------------


@st.cache_resource(show_spinner="Loading model …")
def _load_model():
    from src.models.train import load_model
    try:
        return load_model("best_model")
    except FileNotFoundError:
        return None


@st.cache_data(show_spinner="Loading simulation results …")
def _load_sim_results() -> pd.DataFrame | None:
    path = PROJECT_ROOT / "results" / "simulation" / "probabilities.csv"
    if not path.exists():
        return None
    return pd.read_csv(path)


@st.cache_data(show_spinner="Loading team profiles …")
def _load_profiles() -> pd.DataFrame | None:
    path = PROJECT_ROOT / "data" / "processed" / "team_profiles.csv"
    if not path.exists():
        return None
    return pd.read_csv(path)


@st.cache_data
def _load_metrics() -> pd.DataFrame | None:
    path = PROJECT_ROOT / "results" / "models" / "metrics.csv"
    if not path.exists():
        return None
    return pd.read_csv(path, index_col=0)


@st.cache_data
def _load_feature_cols() -> list[str]:
    path = PROJECT_ROOT / "results" / "models" / "feature_columns.txt"
    if not path.exists():
        return []
    return path.read_text().strip().split("\n")


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------
with st.sidebar:
    st.title("⚽ WC 2026 Predictor")
    st.markdown(
        """
        **FIFA World Cup 2026** probability estimates generated by a
        machine learning model trained on international football results
        from 1980 to present.

        **Pipeline:**
        1. Elo ratings (from 1872)
        2. Rolling form features (last 5 & 10 matches)
        3. FIFA rankings
        4. XGBoost / RF / Logistic Regression
        5. 10 000 Monte Carlo simulations
        """
    )
    st.divider()
    st.caption("⚠️ Group assignments are a placeholder. Update `src/simulation/wc2026_config.py` with the actual draw results.")

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
model = _load_model()
sim_results = _load_sim_results()
profiles_df = _load_profiles()
metrics_df = _load_metrics()
feature_cols = _load_feature_cols()

# ---------------------------------------------------------------------------
# Tabs
# ---------------------------------------------------------------------------
tab1, tab2, tab3, tab4 = st.tabs([
    "🏆 Tournament Predictor",
    "⚽ Match Predictor",
    "📊 Team Rankings",
    "🔬 Model Performance",
])

# ===========================================================================
# TAB 1 — Tournament Predictor
# ===========================================================================
with tab1:
    st.header("FIFA World Cup 2026 — Advancement Probabilities")

    if sim_results is None:
        st.warning("Simulation results not found.  Run `python run_phase6_simulation.py` first.")
    else:
        stage_cols = [c for c in sim_results.columns if c != "team"]

        # Metric strip — top 5 win probability teams
        top5 = sim_results.nlargest(5, "winner")
        cols = st.columns(5)
        for col, (_, row) in zip(cols, top5.iterrows()):
            col.metric(
                label=row["team"],
                value=f"{row['winner']:.1%}",
                delta=f"Final: {row['final']:.1%}",
            )

        st.divider()

        # Interactive heatmap via Plotly
        top_n = st.slider("Teams to display", 16, 48, 32, step=8)
        top = sim_results.nlargest(top_n, "winner").set_index("team")[stage_cols]

        fig = px.imshow(
            top.values * 100,
            x=[c.replace("_", " ").title() for c in stage_cols],
            y=top.index.tolist(),
            color_continuous_scale="YlOrRd",
            text_auto=".0f",
            aspect="auto",
            labels={"color": "Probability (%)"},
            title=f"Advancement Probabilities — Top {top_n} Teams",
            zmin=0,
            zmax=100,
        )
        fig.update_layout(height=max(500, top_n * 18), font_size=11)
        st.plotly_chart(fig, use_container_width=True)

        st.divider()
        st.subheader("Full Probability Table")
        display = sim_results.copy()
        for col in stage_cols:
            display[col] = display[col].map(lambda x: f"{x:.1%}")
        st.dataframe(display, use_container_width=True, hide_index=True)


# ===========================================================================
# TAB 2 — Match Predictor
# ===========================================================================
with tab2:
    st.header("Head-to-Head Match Predictor")

    if model is None or profiles_df is None:
        st.warning(
            "Model or team profiles not found.  "
            "Run `run_phase4_models.py` and `run_phase6_simulation.py` first."
        )
    else:
        teams_available = sorted(profiles_df["team"].dropna().unique().tolist())

        col1, col2 = st.columns(2)
        with col1:
            home_team = st.selectbox("Home Team", teams_available,
                                     index=teams_available.index("Brazil") if "Brazil" in teams_available else 0)
        with col2:
            away_team = st.selectbox("Away Team", teams_available,
                                     index=teams_available.index("Argentina") if "Argentina" in teams_available else 1)

        is_neutral = st.checkbox("Neutral Venue", value=True)
        t_weight = st.slider("Tournament Weight", 0.3, 1.0, 1.0, 0.05,
                              help="1.0 = World Cup, 0.3 = Friendly")

        if st.button("⚽ Predict", type="primary"):
            if home_team == away_team:
                st.error("Please select two different teams.")
            else:
                from src.simulation.monte_carlo import TeamProfile, predict_match_proba

                def _get_profile(name: str) -> TeamProfile:
                    row = profiles_df[profiles_df["team"] == name]
                    if row.empty:
                        return TeamProfile(name=name, elo=1350.0)
                    r = row.iloc[0]
                    return TeamProfile(
                        name=name,
                        elo=float(r.get("elo", 1350)),
                        last5_win=float(r.get("last5_win", 0.4)),
                        last5_gf=float(r.get("last5_gf", 1.4)),
                        last5_ga=float(r.get("last5_ga", 1.4)),
                        last10_win=float(r.get("last10_win", 0.4)),
                        last10_gf=float(r.get("last10_gf", 1.4)),
                        last10_ga=float(r.get("last10_ga", 1.4)),
                        rank=r.get("rank") if pd.notna(r.get("rank", None)) else None,
                        rank_points=r.get("rank_points") if pd.notna(r.get("rank_points", None)) else None,
                    )

                hp = _get_profile(home_team)
                ap = _get_profile(away_team)

                proba = predict_match_proba(hp, ap, model, feature_cols, is_neutral, t_weight)
                p_away, p_draw, p_home = float(proba[0]), float(proba[1]), float(proba[2])

                c1, c2, c3 = st.columns(3)
                c1.metric(f"{home_team} Win", f"{p_home:.1%}")
                c2.metric("Draw", f"{p_draw:.1%}")
                c3.metric(f"{away_team} Win", f"{p_away:.1%}")

                # Bar chart
                fig = go.Figure(go.Bar(
                    x=[f"{home_team} Win", "Draw", f"{away_team} Win"],
                    y=[p_home * 100, p_draw * 100, p_away * 100],
                    marker_color=["#2196F3", "#9E9E9E", "#F44336"],
                    text=[f"{v:.1f}%" for v in [p_home * 100, p_draw * 100, p_away * 100]],
                    textposition="outside",
                ))
                fig.update_layout(
                    title=f"{home_team} vs {away_team} — Predicted Probabilities",
                    yaxis_title="Probability (%)",
                    yaxis_range=[0, 100],
                    height=380,
                )
                st.plotly_chart(fig, use_container_width=True)

                # Elo context
                elo_diff = hp.elo - ap.elo
                st.info(
                    f"**Elo context:** {home_team} ({hp.elo:.0f}) vs "
                    f"{away_team} ({ap.elo:.0f}) — "
                    f"difference: {elo_diff:+.0f} points."
                )


# ===========================================================================
# TAB 3 — Team Rankings
# ===========================================================================
with tab3:
    st.header("Current Team Elo Ratings")

    if profiles_df is None:
        st.warning("Team profiles not found.  Run `python run_phase6_simulation.py` first.")
    else:
        top_n = st.slider("Number of teams", 20, 60, 30, key="elo_slider")
        top = profiles_df.nlargest(top_n, "elo").sort_values("elo", ascending=True)

        fig = px.bar(
            top,
            x="elo",
            y="team",
            orientation="h",
            title=f"Top {top_n} International Teams by Elo Rating",
            labels={"elo": "Elo Rating", "team": ""},
            color="elo",
            color_continuous_scale="Blues",
        )
        fig.add_vline(x=1500, line_dash="dot", line_color="black",
                      annotation_text="Global average (1500)")
        fig.update_layout(height=max(500, top_n * 22), showlegend=False)
        st.plotly_chart(fig, use_container_width=True)

        st.divider()
        st.subheader("Form Statistics (Last 5 Matches)")
        form_cols = ["team", "elo", "last5_win", "last5_gf", "last5_ga", "rank"]
        available = [c for c in form_cols if c in profiles_df.columns]
        form_df = (
            profiles_df[available]
            .sort_values("elo", ascending=False)
            .head(30)
            .reset_index(drop=True)
        )
        # Format rates as percentages
        if "last5_win" in form_df.columns:
            form_df["last5_win"] = form_df["last5_win"].map(lambda x: f"{x:.0%}")
        st.dataframe(form_df, use_container_width=True, hide_index=True)


# ===========================================================================
# TAB 4 — Model Performance
# ===========================================================================
with tab4:
    st.header("Model Performance & Evaluation")

    if metrics_df is None:
        st.warning("Metrics not found.  Run `python run_phase4_models.py` first.")
    else:
        st.subheader("Validation Set Comparison")

        # Reset index so Styler gets a unique RangeIndex (required by pandas)
        _m = metrics_df.reset_index()
        _numeric = [c for c in _m.columns if _m[c].dtype.kind == "f"]
        styled = _m.style.background_gradient(
            subset=[c for c in ["log_loss", "brier_score"] if c in _m.columns],
            cmap="RdYlGn_r",
        ).background_gradient(
            subset=[c for c in ["accuracy", "f1_macro"] if c in _m.columns],
            cmap="RdYlGn",
        ).format("{:.4f}", subset=_numeric)
        st.dataframe(styled, use_container_width=True)

        st.divider()
        st.subheader("Metric Glossary")
        st.markdown("""
| Metric | What it measures | Lower is better? |
|---|---|---|
| **accuracy** | Fraction of correct outcome predictions (home/draw/away) | No — higher |
| **log_loss** | Quality of predicted probabilities (cross-entropy) | Yes |
| **brier_score** | Mean squared probability error (calibration) | Yes |
| **f1_macro** | Balanced F1 across all three outcome classes | No — higher |
| **precision_weighted** | Weighted precision across classes | No — higher |
| **recall_weighted** | Weighted recall across classes | No — higher |

> **Key insight:** Log loss and Brier score matter most for this project because
> the Monte Carlo simulation uses raw predicted probabilities.
> A model with 70% accuracy but poor calibration will generate misleading
> tournament probability estimates.
        """)

        st.divider()
        col1, col2 = st.columns(2)
        with col1:
            st.subheader("Calibration Plot")
            cal_path = PROJECT_ROOT / "results" / "phase4" / "calibration_curves.png"
            if cal_path.exists():
                st.image(str(cal_path), use_column_width=True)
            else:
                st.info("Run Phase 4 to generate the calibration plot.")

        with col2:
            st.subheader("Feature Importance")
            fi_path = PROJECT_ROOT / "results" / "phase7" / "05_feature_importance.png"
            if fi_path.exists():
                st.image(str(fi_path), use_column_width=True)
            else:
                st.info("Run Phase 7 to generate the feature importance plot.")
